### ISSUE TITLE
Pass other command-line openvpn args possible?

### ISSUE THREAD

**Issue by Denio888** [slingamn/namespaced-openvpn#20]
Is it possible to pass other command-line openvpn args with the namespaced-openvpn script?
I see namespaced-openvpn takes these argument --config.

Is it possible to pass other openvpn arguments from the client.ovpn file directly to namespaced-openvpn?
Like this: namespaced-openvpn --config vpn.ovpn --(other openvpn argument like –proto udp)
So i don`t have to edit each .ovpn file and change these values.

**Comment by slingamn** [comment]
Yep! You can pass arbitrary openvpn args on the command line, nost just `--config`. (`--route-up` has some edge cases; see the "TODO" section of the readme.)
