### ISSUE TITLE
torified version possible?

### ISSUE THREAD

**Issue by mgaulton** [slingamn/namespaced-openvpn#25]
For some instances, I need to tor so I was reading this wiki and wonder if this could be adapted.

https://github.com/ambrop72/badvpn/wiki/Tun2socks

**Comment by slingamn** [comment]
I would think a better technique is to create a new network namespace with no adapters, and let applications in it SOCKS to the Tor daemon over Unix domain socket only. (I think the torrc directive is `SocksPort unix:/path/to/socks/port`.)

**Comment by mgaulton** [comment]
Ok, I hadn't thought of that. I was thinking just to isolate it in the
namespace completely so my root namespace doesn't even see it :)

I'll give that a go
