### ISSUE TITLE
No connectivity in protected namespace as unprivileged

### ISSUE THREAD

**Issue by Linden6** [slingamn/namespaced-openvpn#28]
I have successfully used namespaced-openvpn for a year or two, but now after having upgraded to the latest testing version of Debian I am experiencing problems running unprivileged applications with it.

I have installed namespaced-openvpn in /usr/local/sbin (-rwxr-xr-x root).

Once the namespace is set up (sudo namespaced-openvpn --config ./my_openvpn_config_file
), if I run ping in the protected namespace as root:
    `sudo ip netns exec protected ping -w 3 www.google.com`
then all is fine.

But, if I run ping in the protected namespace as user:
    `sudo ip netns exec protected sudo -u $USER ping -w 3 www.google.com`
then I have no connection and get 'ping: www.google.com: Name or service not known'.

I have no connectivity running all other applications in the protected namespace unprivileged - apart from, for some reason, Tor.

Unfortunately, I don't have a great deal of expertise in this area and haven't been able to find the cause, and so any pointers would be gratefully received.

**Comment by slingamn** [comment]
Thanks for the report!

This appears to be a failure of name resolution when running unprivileged. Are you using systemd-resolved? If so, you should disable it as described here: https://github.com/slingamn/namespaced-openvpn#dns-hardening

If that's not the problem, try the following commands:

```
sudo ip netns exec protected python3 -c "import socket; print(socket.gethostbyname('www.google.com'))"

sudo ip netns exec protected sudo -u $USER -i python3 -c "import socket; print(socket.gethostbyname('www.google.com'))"

sudo ip netns exec protected strace python3 -c "import socket; print(socket.gethostbyname('www.google.com'))

sudo ip netns exec protected sudo -u $USER strace python3 -c "import socket; print(socket.gethostbyname('www.google.com'))"
```

These attempt to do a "vanilla" name resolution with Python, first in the namespace as root, then in the namespace as the current (presumably unprivileged) user. The commands with `strace` in them should provide detailed information about what operations are occurring and which ones are failing.

**Comment by Linden6** [comment]
I was using systemd-resolved, but disabling it didn't unfortunately resolve the problem.

However, using the strace tool I found the following line:

> openat(AT_FDCWD, "/etc/resolv.conf", O_RDONLY|O_CLOEXEC) = -1 EACCES (Permission denied)

Looking at permissions, `sudo ip netns exec protected ls -la /etc/resolv.conf` yielded:
-rw------- 1 root root 45 Mar 13 18:31 /etc/resolv.conf
so only root could access the address of the dns resolver.

I've changed the permissions to '-rw-r--r--' and I can now use the protected namespace unprivileged to connect to the internet.  Even after removing and recreating the 'protected' namespace, and shutting down and restarting my computer, everything now works as it should.

However, I'm not sure what I did to cause the problem in the first place.

Thanks - without your help I would never have got to the root of the problem!

**Comment by slingamn** [comment]
Interesting, thanks.

Try stopping namespaced-openvpn, deleting `/etc/netns/protected/resolv.conf`, restarting it, and seeing if the problem comes back? That file actually persists across reboots, so the issue might not be fixed.

**Comment by Linden6** [comment]
Although changing resolv.conf permissions remedies the problem, the problem does persist when totally removing namespaced-open and reinstalling it:

Stop namespaced-openvpn:
`sudo ip netns del protected`

Delete protected resolv.conf:
`sudo rm /etc/netns/protected/resolv.conf`

Delete executable:
`sudo rm /usr/local/sbin/namespaced-openvpn`

Download, extract, and installfresh copy of namespaced-openvpn to /tmp:
```
cd /tmp/namespaced-openvpn-master
make
sudo make install
```
 
Start namespaced-openvpn:
`sudo namespaced-openvpn --config $ovpnFile --daemon`

Check permssions:
`sudo ls -la /etc/netns/protected/resolv.conf`

> -rw------- 1 root root 45 Mar 14 09:49 /etc/netns/protected/resolv.conf


---

These are the permissions in the /tmp folder where namespaced-openvpn extracted:
`ls -la /tmp/namespaced-openvpn-master`

> total 72
> drwx------  3 angus angus  4096 Dec  6 10:05 .
> drwxrwxrwt 27 root  root   4096 Mar 14 09:51 ..
> -rw-r--r--  1 angus angus    12 Dec  6 10:05 .gitignore
> -rw-r--r--  1 angus angus  1062 Dec  6 10:05 LICENSE
> -rw-r--r--  1 angus angus   255 Dec  6 10:05 Makefile
> -rwxr-xr-x  1 angus angus 14678 Dec  6 10:05 namespaced-openvpn
> -rw-r--r--  1 angus angus 22372 Dec  6 10:05 README.md
> -rwxr-xr-x  1 angus angus   657 Dec  6 10:05 seal-unseal-gateway
> -rw-r--r--  1 angus angus    30 Dec  6 10:05 setup.cfg
> drwx------  3 angus angus  4096 Mar 14 09:46 tests

This is the permission for the executable:

> -rwxr-xr-x 1 root root 14678 Mar 14 09:46 /usr/local/sbin/namespaced-openvpn

---

It would be helpful to know if I am taking a wrong turn at some point leading to the problem, or whether there is a wider issue that may affect others.  Thanks!

**Comment by slingamn** [comment]
It sounds like this issue will affect other people, although I'm not sure what the root cause is yet.

Reinstalling `/usr/local/sbin/namespaced-openvpn` shouldn't affect anything. Does the problem reproduce if you leave the executable in place, but stop the process and delete `/etc/netns/protected/resolv.conf`?

If so, the problem is most likely just that the file is created with the wrong permissions. See if the problem reproduces without `--daemon`? Also, try `strace -ff sudo namespaced-openvpn --config $ovpnFile` and see if there's a call to `umask(2)` (that's what controls the permissions of newly created files).

**Comment by Linden6** [comment]
Hi - I've managed to track down the source of the problem, and am more than a little embarrassed as it has nothing to do with your code.

I was running the 'sudo namespaced-openvpn --config $ovpnFile' command in an Emacs Org-mode code-block.  When run directly in a terminal the resolv.conf permissions were normal.

(I've yet to get to the bottom of the elisp code-block code, but it is obviously here that the permissions are being affected.)

Thanks for all your trouble.

**Comment by slingamn** [comment]
No worries, thanks for the report!
